version: "3"

services:
  php:
    build:
      context: .
      dockerfile: php-dockerfile # PHP FPM
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb

  nginx:
    image: docker.io/nginx:alpine
    ports:
      # If you want to change the used port, modify the first one
      - 1080:80 # Nginx+Php server
      - 1088:8080 # Phpmyadmin
      - 8888:8888/udp # Arduino
      - 8888:8888/tcp # Arduino
    volumes:
      - ./app:/var/www/html
      - ./config/nginx:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx
      - phpmyadmindata:/var/www/phpmyadmin
    depends_on:
      - php

  mariadb:
    image: docker.io/mariadb
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./log/mariadb:/var/log/mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root

  phpmyadmin:
    image: docker.io/phpmyadmin:fpm-alpine
    volumes:
      - phpmyadmindata:/var/www/html
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mariadb

  node:
    image: docker.io/node:alpine
    #user: node
    working_dir: /var/node/app
    volumes:
      - ./app:/var/node/app
    command: sh -c "npm install && npm run build:tailwind && npm run build:css && tail -f /dev/null"

volumes:
  mariadbdata:
  phpmyadmindata:
